-- KnowNote 用户表
CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `email` VARCHAR(255) NOT NULL UNIQUE COMMENT '邮箱',
    `username` VARCHAR(13) UNIQUE COMMENT '用户ID，最长13字符',
    `nickname` VARCHAR(64) COMMENT '昵称',
    `password_hash` VARCHAR(255) COMMENT '密码哈希（BCrypt）',
    `google_id` VARCHAR(255) UNIQUE COMMENT 'Google OpenID',
    `avatar` VARCHAR(512) COMMENT '头像URL',
    `bio` VARCHAR(200) COMMENT '个人简介',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- KnowNote 笔记表
CREATE TABLE IF NOT EXISTS `post` (
    `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    `creator_id` BIGINT UNSIGNED NOT NULL COMMENT '创建者ID',
    `status` VARCHAR(20) NOT NULL COMMENT '状态（DRAFT, REVIEWING, PUBLISHED, DELETED, REJECTED）',
    `type` VARCHAR(20) NOT NULL COMMENT '类型（article）',
    `title` VARCHAR(255) COMMENT '标题',
    `description` VARCHAR(512) COMMENT '描述',
    `tags` JSON COMMENT '标签，逗号分隔',
    `cover_url` VARCHAR(512) COMMENT '封面URL',
    `img_urls` JSON COMMENT '图片URL列表',
    `is_top` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否置顶',
    `content_url` VARCHAR(512) COMMENT '内容存储URL',
    `content_sha256` CHAR(64) COMMENT '内容SHA-256哈希',
    `reject_reason` VARCHAR(512) COMMENT '拒绝原因',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `published_at` DATETIME COMMENT '发布时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='帖子表';